# -*- coding: utf-8 -*-
# This is an auto-generated Django model module.

from rest_framework_fine_permissions.serializers import ModelPermissionsSerializer
from django.conf.urls import patterns, url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = patterns('',
url(r'^authgroup/(?P<pk>\w+)$', views.AuthGroupDetail.as_view(), name='authgroup-all-detail'),
url(r'^authgroup$', views.AuthGroupList.as_view(), name='authgroup-all-list'),
url(r'^authgrouppermissions/(?P<pk>\w+)$', views.AuthGroupPermissionsDetail.as_view(), name='authgrouppermissions-all-detail'),
url(r'^authgrouppermissions$', views.AuthGroupPermissionsList.as_view(), name='authgrouppermissions-all-list'),
url(r'^authpermission/(?P<pk>\w+)$', views.AuthPermissionDetail.as_view(), name='authpermission-all-detail'),
url(r'^authpermission$', views.AuthPermissionList.as_view(), name='authpermission-all-list'),
url(r'^authuser/(?P<pk>\w+)$', views.AuthUserDetail.as_view(), name='authuser-all-detail'),
url(r'^authuser$', views.AuthUserList.as_view(), name='authuser-all-list'),
url(r'^authusergroups/(?P<pk>\w+)$', views.AuthUserGroupsDetail.as_view(), name='authusergroups-all-detail'),
url(r'^authusergroups$', views.AuthUserGroupsList.as_view(), name='authusergroups-all-list'),
url(r'^authuseruserpermissions/(?P<pk>\w+)$', views.AuthUserUserPermissionsDetail.as_view(), name='authuseruserpermissions-all-detail'),
url(r'^authuseruserpermissions$', views.AuthUserUserPermissionsList.as_view(), name='authuseruserpermissions-all-list'),
url(r'^authtokentoken/(?P<pk>\w+)$', views.AuthtokenTokenDetail.as_view(), name='authtokentoken-all-detail'),
url(r'^authtokentoken$', views.AuthtokenTokenList.as_view(), name='authtokentoken-all-list'),
url(r'^captchacaptchastore/(?P<pk>\w+)$', views.CaptchaCaptchastoreDetail.as_view(), name='captchacaptchastore-all-detail'),
url(r'^captchacaptchastore$', views.CaptchaCaptchastoreList.as_view(), name='captchacaptchastore-all-list'),
url(r'^corecontactus/(?P<pk>\w+)$', views.CoreContactusDetail.as_view(), name='corecontactus-all-detail'),
url(r'^corecontactus$', views.CoreContactusList.as_view(), name='corecontactus-all-list'),
url(r'^coreencodingtype/(?P<pk>\w+)$', views.CoreEncodingtypeDetail.as_view(), name='coreencodingtype-all-detail'),
url(r'^coreencodingtype$', views.CoreEncodingtypeList.as_view(), name='coreencodingtype-all-list'),
url(r'^corefilebrowse/(?P<pk>\w+)$', views.CoreFilebrowseDetail.as_view(), name='corefilebrowse-all-detail'),
url(r'^corefilebrowse$', views.CoreFilebrowseList.as_view(), name='corefilebrowse-all-list'),
url(r'^corepagesmenubas/(?P<pk>\w+)$', views.CorePagesmenubasDetail.as_view(), name='corepagesmenubas-all-detail'),
url(r'^corepagesmenubas$', views.CorePagesmenubasList.as_view(), name='corepagesmenubas-all-list'),
url(r'^coreuserprofile/(?P<pk>\w+)$', views.CoreUserprofileDetail.as_view(), name='coreuserprofile-all-detail'),
url(r'^coreuserprofile$', views.CoreUserprofileList.as_view(), name='coreuserprofile-all-list'),
url(r'^djangoadminlog/(?P<pk>\w+)$', views.DjangoAdminLogDetail.as_view(), name='djangoadminlog-all-detail'),
url(r'^djangoadminlog$', views.DjangoAdminLogList.as_view(), name='djangoadminlog-all-list'),
url(r'^djangocontenttype/(?P<pk>\w+)$', views.DjangoContentTypeDetail.as_view(), name='djangocontenttype-all-detail'),
url(r'^djangocontenttype$', views.DjangoContentTypeList.as_view(), name='djangocontenttype-all-list'),
url(r'^djangoflatpage/(?P<pk>\w+)$', views.DjangoFlatpageDetail.as_view(), name='djangoflatpage-all-detail'),
url(r'^djangoflatpage$', views.DjangoFlatpageList.as_view(), name='djangoflatpage-all-list'),
url(r'^djangoflatpagesites/(?P<pk>\w+)$', views.DjangoFlatpageSitesDetail.as_view(), name='djangoflatpagesites-all-detail'),
url(r'^djangoflatpagesites$', views.DjangoFlatpageSitesList.as_view(), name='djangoflatpagesites-all-list'),
url(r'^djangomigrations/(?P<pk>\w+)$', views.DjangoMigrationsDetail.as_view(), name='djangomigrations-all-detail'),
url(r'^djangomigrations$', views.DjangoMigrationsList.as_view(), name='djangomigrations-all-list'),
url(r'^djangosession/(?P<pk>\w+)$', views.DjangoSessionDetail.as_view(), name='djangosession-all-detail'),
url(r'^djangosession$', views.DjangoSessionList.as_view(), name='djangosession-all-list'),
url(r'^djangosite/(?P<pk>\w+)$', views.DjangoSiteDetail.as_view(), name='djangosite-all-detail'),
url(r'^djangosite$', views.DjangoSiteList.as_view(), name='djangosite-all-list'),
url(r'^easythumbnailssource/(?P<pk>\w+)$', views.EasyThumbnailsSourceDetail.as_view(), name='easythumbnailssource-all-detail'),
url(r'^easythumbnailssource$', views.EasyThumbnailsSourceList.as_view(), name='easythumbnailssource-all-list'),
url(r'^easythumbnailsthumbnail/(?P<pk>\w+)$', views.EasyThumbnailsThumbnailDetail.as_view(), name='easythumbnailsthumbnail-all-detail'),
url(r'^easythumbnailsthumbnail$', views.EasyThumbnailsThumbnailList.as_view(), name='easythumbnailsthumbnail-all-list'),
url(r'^easythumbnailsthumbnaildimensions/(?P<pk>\w+)$', views.EasyThumbnailsThumbnaildimensionsDetail.as_view(), name='easythumbnailsthumbnaildimensions-all-detail'),
url(r'^easythumbnailsthumbnaildimensions$', views.EasyThumbnailsThumbnaildimensionsList.as_view(), name='easythumbnailsthumbnaildimensions-all-list'),
url(r'^filerclipboard/(?P<pk>\w+)$', views.FilerClipboardDetail.as_view(), name='filerclipboard-all-detail'),
url(r'^filerclipboard$', views.FilerClipboardList.as_view(), name='filerclipboard-all-list'),
url(r'^filerclipboarditem/(?P<pk>\w+)$', views.FilerClipboarditemDetail.as_view(), name='filerclipboarditem-all-detail'),
url(r'^filerclipboarditem$', views.FilerClipboarditemList.as_view(), name='filerclipboarditem-all-list'),
url(r'^filerfile/(?P<pk>\w+)$', views.FilerFileDetail.as_view(), name='filerfile-all-detail'),
url(r'^filerfile$', views.FilerFileList.as_view(), name='filerfile-all-list'),
url(r'^filerfolder/(?P<pk>\w+)$', views.FilerFolderDetail.as_view(), name='filerfolder-all-detail'),
url(r'^filerfolder$', views.FilerFolderList.as_view(), name='filerfolder-all-list'),
url(r'^filerfolderpermission/(?P<pk>\w+)$', views.FilerFolderpermissionDetail.as_view(), name='filerfolderpermission-all-detail'),
url(r'^filerfolderpermission$', views.FilerFolderpermissionList.as_view(), name='filerfolderpermission-all-list'),
url(r'^filerimage/(?P<pk>\w+)$', views.FilerImageDetail.as_view(), name='filerimage-all-detail'),
url(r'^filerimage$', views.FilerImageList.as_view(), name='filerimage-all-list'),
url(r'^podsbuilding/(?P<pk>\w+)$', views.PodsBuildingDetail.as_view(), name='podsbuilding-all-detail'),
url(r'^podsbuilding$', views.PodsBuildingList.as_view(), name='podsbuilding-all-list'),
url(r'^podschannel/(?P<pk>\w+)$', views.PodsChannelDetail.as_view(), name='podschannel-all-detail'),
url(r'^podschannel$', views.PodsChannelList.as_view(), name='podschannel-all-list'),
url(r'^podschannelowners/(?P<pk>\w+)$', views.PodsChannelOwnersDetail.as_view(), name='podschannelowners-all-detail'),
url(r'^podschannelowners$', views.PodsChannelOwnersList.as_view(), name='podschannelowners-all-list'),
url(r'^podschannelusers/(?P<pk>\w+)$', views.PodsChannelUsersDetail.as_view(), name='podschannelusers-all-detail'),
url(r'^podschannelusers$', views.PodsChannelUsersList.as_view(), name='podschannelusers-all-list'),
url(r'^podschapterpods/(?P<pk>\w+)$', views.PodsChapterpodsDetail.as_view(), name='podschapterpods-all-detail'),
url(r'^podschapterpods$', views.PodsChapterpodsList.as_view(), name='podschapterpods-all-list'),
url(r'^podscontributorpods/(?P<pk>\w+)$', views.PodsContributorpodsDetail.as_view(), name='podscontributorpods-all-detail'),
url(r'^podscontributorpods$', views.PodsContributorpodsList.as_view(), name='podscontributorpods-all-list'),
url(r'^podsdiscipline/(?P<pk>\w+)$', views.PodsDisciplineDetail.as_view(), name='podsdiscipline-all-detail'),
url(r'^podsdiscipline$', views.PodsDisciplineList.as_view(), name='podsdiscipline-all-list'),
url(r'^podsdocpods/(?P<pk>\w+)$', views.PodsDocpodsDetail.as_view(), name='podsdocpods-all-detail'),
url(r'^podsdocpods$', views.PodsDocpodsList.as_view(), name='podsdocpods-all-list'),
url(r'^podsencodingpods/(?P<pk>\w+)$', views.PodsEncodingpodsDetail.as_view(), name='podsencodingpods-all-detail'),
url(r'^podsencodingpods$', views.PodsEncodingpodsList.as_view(), name='podsencodingpods-all-list'),
url(r'^podsenrichpods/(?P<pk>\w+)$', views.PodsEnrichpodsDetail.as_view(), name='podsenrichpods-all-detail'),
url(r'^podsenrichpods$', views.PodsEnrichpodsList.as_view(), name='podsenrichpods-all-list'),
url(r'^podsfavorites/(?P<pk>\w+)$', views.PodsFavoritesDetail.as_view(), name='podsfavorites-all-detail'),
url(r'^podsfavorites$', views.PodsFavoritesList.as_view(), name='podsfavorites-all-list'),
url(r'^podsmediacourses/(?P<pk>\w+)$', views.PodsMediacoursesDetail.as_view(), name='podsmediacourses-all-detail'),
url(r'^podsmediacourses$', views.PodsMediacoursesList.as_view(), name='podsmediacourses-all-list'),
url(r'^podsnotes/(?P<pk>\w+)$', views.PodsNotesDetail.as_view(), name='podsnotes-all-detail'),
url(r'^podsnotes$', views.PodsNotesList.as_view(), name='podsnotes-all-list'),
url(r'^podspod/(?P<pk>\w+)$', views.PodsPodDetail.as_view(), name='podspod-all-detail'),
url(r'^podspod$', views.PodsPodList.as_view(), name='podspod-all-list'),
url(r'^podspodchannel/(?P<pk>\w+)$', views.PodsPodChannelDetail.as_view(), name='podspodchannel-all-detail'),
url(r'^podspodchannel$', views.PodsPodChannelList.as_view(), name='podspodchannel-all-list'),
url(r'^podspoddiscipline/(?P<pk>\w+)$', views.PodsPodDisciplineDetail.as_view(), name='podspoddiscipline-all-detail'),
url(r'^podspoddiscipline$', views.PodsPodDisciplineList.as_view(), name='podspoddiscipline-all-list'),
url(r'^podspodtheme/(?P<pk>\w+)$', views.PodsPodThemeDetail.as_view(), name='podspodtheme-all-detail'),
url(r'^podspodtheme$', views.PodsPodThemeList.as_view(), name='podspodtheme-all-list'),
url(r'^podsrecorder/(?P<pk>\w+)$', views.PodsRecorderDetail.as_view(), name='podsrecorder-all-detail'),
url(r'^podsrecorder$', views.PodsRecorderList.as_view(), name='podsrecorder-all-list'),
url(r'^podsreportvideo/(?P<pk>\w+)$', views.PodsReportvideoDetail.as_view(), name='podsreportvideo-all-detail'),
url(r'^podsreportvideo$', views.PodsReportvideoList.as_view(), name='podsreportvideo-all-list'),
url(r'^podstheme/(?P<pk>\w+)$', views.PodsThemeDetail.as_view(), name='podstheme-all-detail'),
url(r'^podstheme$', views.PodsThemeList.as_view(), name='podstheme-all-list'),
url(r'^podstrackpods/(?P<pk>\w+)$', views.PodsTrackpodsDetail.as_view(), name='podstrackpods-all-detail'),
url(r'^podstrackpods$', views.PodsTrackpodsList.as_view(), name='podstrackpods-all-list'),
url(r'^podstype/(?P<pk>\w+)$', views.PodsTypeDetail.as_view(), name='podstype-all-detail'),
url(r'^podstype$', views.PodsTypeList.as_view(), name='podstype-all-list'),
url(r'^taggittag/(?P<pk>\w+)$', views.TaggitTagDetail.as_view(), name='taggittag-all-detail'),
url(r'^taggittag$', views.TaggitTagList.as_view(), name='taggittag-all-list'),
url(r'^taggittaggeditem/(?P<pk>\w+)$', views.TaggitTaggeditemDetail.as_view(), name='taggittaggeditem-all-detail'),
url(r'^taggittaggeditem$', views.TaggitTaggeditemList.as_view(), name='taggittaggeditem-all-list'),
url(r'^taggittemplatetagsamodel/(?P<pk>\w+)$', views.TaggitTemplatetagsAmodelDetail.as_view(), name='taggittemplatetagsamodel-all-detail'),
url(r'^taggittemplatetagsamodel$', views.TaggitTemplatetagsAmodelList.as_view(), name='taggittemplatetagsamodel-all-list'),
# Special routes for sympa
url(r'^mailinglist/(?P<type>\w+)/$', views.mailing_list, name='mailinglist'),
)

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])
